dist: trusty
language: tex
sudo: false

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-generic-recommended
      - texlive-fonts-recommended

env:
  global:
  matrix:

matrix:
  allow_failures:
    # - env: LISP=clisp

install:

cache:
  directories:

script:
  - make submission

